trigger:
  - dev

pool:
  name: 'Default'

variables:
  skipComponentGovernanceDetection: "true"

steps:
  - task: CopyFiles@2
    displayName: "Stage Files"
    inputs:
      SourceFolder: "$(Build.SourcesDirectory)"
      Contents: |
        **/*
        !.git/**/*
        !ip.txt
      TargetFolder: "$(Build.ArtifactStagingDirectory)"

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact"
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "platform"
      publishLocation: "Container"
